spring.application.name=back

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/purchasing_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

---
spring.config.activate.on-profile=docker

# Docker MySQL Configuration
spring.datasource.url=jdbc:mysql://db:3306/purchase_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
